version: '2'

networks:
  ISP:
    ipam:
      driver: default
      config:
        - subnet: 72.28.0.0/16
          ip_range: 72.28.1.0/30
          gateway: 72.28.1.1
          aux_addresses:
            host1: 72.28.1.2
            host2: 72.28.1.3
  x1:
    driver: bridge
    driver_opts: 
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      driver: default
      config:
        - subnet: 42.28.0.0/16
          ip_range: 42.28.1.0/30
          gateway: 42.28.1.1
          aux_addresses:
            host1: 42.28.1.2
            host2: 42.28.1.3
  x2:
    driver: bridge
    driver_opts: 
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      driver: default
      config:
        - subnet: 22.28.0.0/16
          ip_range: 22.28.1.0/30
          gateway: 22.28.1.1
          aux_addresses:
            host1: 22.28.1.2
            host2: 22.28.1.3


services:
  dhcpclientx1:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclientx1
    container_name: dhcpclientx1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 42.28.1.101

  dhcpclientx2:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclientx2
    container_name: dhcpclientx2
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x2:
        ipv4_address: 22.28.1.101

  dhcpserver:
    image: joaniznardo/ubuntum7dhcp1
    privileged: true
    mem_limit: 100m
    hostname: dhcpserver
    container_name: dhcpserver
    networks:
      x1:
        ipv4_address: 42.28.1.120
  
  homerouter:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: homerouter
    container_name: homerouter
    networks:
      ISP:
        ipv4_address: 72.28.1.100
      x1:
        ipv4_address: 42.28.1.100
  
  dhcprelay:
    image: joaniznardo/ubuntum7dhcp1
    privileged: true
    mem_limit: 100m
    hostname: dhcprelay 
    container_name: dhcprelay 
    networks:
      x1:
        ipv4_address: 42.28.1.99 
      x2:
        ipv4_address: 22.28.1.100
  
