version: '2'

services:
  
  dhcpclient_5:
    image: joaniznardo/ubuntum7base
    hostname: dhcpclient05
    container_name: dhcpclient05
    privileged: true
    mem_limit: 100m
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
       ipv4_address: 72.28.1.105

  dhcpclient_4:
    image: joaniznardo/ubuntum7base
    hostname: dhcpclient04
    container_name: dhcpclient04
    privileged: true
    mem_limit: 100m
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
       ipv4_address: 72.28.1.104

  dhcpclient_3:
    image: joaniznardo/ubuntum7base
    hostname: dhcpclient03
    container_name: dhcpclient03
    privileged: true
    mem_limit: 100m
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
       ipv4_address: 72.28.1.103

  dhcpclient_2:
    image: joaniznardo/ubuntum7base
    hostname: dhcpclient02
    container_name: dhcpclient02
    privileged: true
    mem_limit: 100m
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
       ipv4_address: 72.28.1.102

  dhcpclient_1:
    image: joaniznardo/ubuntum7base
    hostname: dhcpclient01
    container_name: dhcpclient01
    privileged: true
    mem_limit: 100m
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
       ipv4_address: 72.28.1.101


  dhcpserver:
    image: joaniznardo/ubuntum7dhcp1
    privileged: true
    mem_limit: 100m
    hostname: dhcpserver
    container_name: dhcpserver
    networks:
      x1:
       ipv4_address: 72.28.1.100
  
networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 72.28.0.0/16
          ip_range: 72.28.1.0/30
          gateway: 72.28.1.1
          aux_addresses:
            host1: 72.28.1.2
            host2: 72.28.1.3
