version: '2'

# la xarxa 1 farà servir les adreces 72.28.1.0/24
# la xarxa 2 farà servir les adreces 42.28.1.0/24
# la xarxa 3 farà servir les adreces 12.28.1.0/24
 

services:
  
  dhcpclientx2:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclientx2
    container_name: dhcpclientx2
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x2:
        ipv4_address: 42.28.1.101

  dhcpclientx3:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclientx3
    container_name: dhcpclientx3
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x3:
        ipv4_address: 12.28.1.101

  dhcpclientx1:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclientx1
    container_name: dhcpclientx1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 72.28.1.101

  dhcpserver:
    image: joaniznardo/ubuntum7dhcp2
    privileged: true
    mem_limit: 100m
    hostname: dhcpserver
    container_name: dhcpserver
    networks:
      x1:
        ipv4_address: 72.28.1.100
  
  dhcprelayx2:
    image: joaniznardo/ubuntum7dhcp3
    privileged: true
    mem_limit: 100m
    hostname: dhcprelayx2
    container_name: dhcprelayx2
    networks:
      x1:
        ipv4_address: 72.28.1.99 
      x2:
        ipv4_address: 42.28.1.100
  
  dhcprelayx3:
    image: joaniznardo/ubuntum7dhcp3
    privileged: true
    mem_limit: 100m
    hostname: dhcprelayx3
    container_name: dhcprelayx3
    networks:
      x1:
        ipv4_address: 72.28.1.98 
      x3:
        ipv4_address: 12.28.1.100
  
networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 72.28.1.0/24
          ip_range: 72.28.1.0/30
          gateway: 72.28.1.1
          aux_addresses:
            host1: 72.28.1.2
            host2: 72.28.1.3

  x2:
    ipam:
      driver: default
      config:
        - subnet: 42.28.1.0/24
          ip_range: 42.28.1.0/30
          gateway: 42.28.1.1
          aux_addresses:
            host1: 42.28.1.2
            host2: 42.28.1.3
  x3:
    ipam:
      driver: default
      config:
        - subnet: 12.28.1.0/24
          ip_range: 12.28.1.0/30
          gateway: 12.28.1.1
          aux_addresses:
            host1: 12.28.1.2
            host2: 12.28.1.3
