version: '2'

services:
  
  dhcpclient:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    depends_on:
      - dhcpserver1
      - dhcpserver2
    command: ["bash", "-c", "/etc/init.d/rsyslog start && ip a flush dev eth0 && dhclient eth0 && supervisord -n"]
#   hostname: dhcpclient1        
#   container_name: dhcpclient1        
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:


  dhcpserver1:
    image: joaniznardo/ubuntum7dhcp2
    privileged: true
    mem_limit: 100m
    command: ["bash", "-c", "/etc/init.d/rsyslog start && /etc/init.d/isc-dhcp-server start && supervisord -n"]
    hostname: dhcpserver1
    container_name: dhcpserver1
    volumes:
      - ./isc-dhcp-server.server1:/etc/default/isc-dhcp-dhcpserver
      - ./dhcpd.conf.server1:/etc/dhcp/dhcpd.conf
    networks:
      x1:
        ipv4_address: 72.28.0.100
  
  dhcpserver2:
    image: joaniznardo/ubuntum7dhcp2
    privileged: true
    mem_limit: 100m
    depends_on:
      - dhcpserver1
    command: ["bash", "-c", "/etc/init.d/rsyslog start && /etc/init.d/isc-dhcp-server start && supervisord -n"]
    hostname: dhcpserver2
    container_name: dhcpserver2
    volumes:
      - ./isc-dhcp-server.server2:/etc/default/isc-dhcp-dhcpserver
      - ./dhcpd.conf.server2:/etc/dhcp/dhcpd.conf
    networks:
      x1:
        ipv4_address: 72.28.0.99
  
networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 72.28.0.0/16
