version: '2'

services:
  
  dhcpclient01:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclient01
    container_name: dhcpclient01
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 72.28.1.101
    
  dhcpclient02:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclient02
    container_name: dhcpclient02
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 72.28.1.102
    
  dhcpclient03:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclient03
    container_name: dhcpclient03
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 72.28.1.103
    
  dhcpclient04:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclient04
    container_name: dhcpclient04
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 72.28.1.104
    
  dhcpclient05:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclient05
    container_name: dhcpclient05
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 72.28.1.105
    
  dnsserver:
    image: joaniznardo/ubuntum7dnsbind
    privileged: true
    mem_limit: 100m
    hostname: dnsserver
    container_name: dnsserver
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 72.28.1.100
  
  dnsserver2:
    image: joaniznardo/ubuntum7dnsbind
    privileged: true
    mem_limit: 100m
    hostname: dnsserver2
    container_name: dnsserver2
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 72.28.1.98
  
  dnsserver3:
    image: joaniznardo/ubuntum7dnsbind
    privileged: true
    mem_limit: 100m
    hostname: dnsserver3
    container_name: dnsserver3
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 72.28.1.97
  
networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 72.28.1.0/24
          ip_range: 72.28.1.0/30
          gateway: 72.28.1.1
          aux_addresses:
            host1: 72.28.1.2
            host2: 72.28.1.3
#
#

