version: '2'

services:
  
  dhcpclient1_x1:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclient1_x1        
    container_name: dhcpclient1_x1        
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 72.28.1.101        

  dhcpclient2_x1:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclient2_x1        
    container_name: dhcpclient2_x1        
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 72.28.1.102        

  dhcpclient1_x2:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclient1_x2        
    container_name: dhcpclient1_x2        
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x2:
        ipv4_address: 22.28.1.101        

  dhcpclient2_x2:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclient2_x2        
    container_name: dhcpclient2_x2        
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x2:
        ipv4_address: 22.28.1.102        

  dhcpserver:
    image: joaniznardo/ubuntum7dhcp2
    privileged: true
    mem_limit: 100m
    hostname: dhcpserver
    container_name: dhcpserver
    networks:
      x1:
        ipv4_address: 72.28.1.100
      x2:
        ipv4_address: 22.28.1.100
  
  
networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 72.28.0.0/16
          ip_range: 72.28.1.0/30
          gateway: 72.28.1.1
          aux_addresses:
            host0: 72.28.1.0
            host1: 72.28.1.2
            host2: 72.28.1.3
  x2:
    ipam:
      driver: default
      config:
        - subnet: 22.28.0.0/16
          ip_range: 22.28.1.0/30
          gateway: 22.28.1.1
          aux_addresses:
            host0: 22.28.1.0
            host1: 22.28.1.2
            host2: 22.28.1.3
